name: playground_for_flutter
description: Appwrite playground is a simple way to explore the Appwrite API &
  Appwrite Flutter SDK. Use the source code of this page to learn how to use the
  different Appwrite Flutter SDK features.

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  appwrite: ^1.0.0
  file_picker: ^3.0.1
  hexcolor: ^2.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true
